/*****************************************************************************
 * Copyright (C) 2023-2025 by Ivan Podmazov                                  *
 *                                                                           *
 * This file is part of Archipelago.                                         *
 *                                                                           *
 *   Archipelago is free software: you can redistribute it and/or modify it  *
 *   under the terms of the GNU Lesser General Public License as published   *
 *   by the Free Software Foundation, either version 3 of the License, or    *
 *   (at your option) any later version.                                     *
 *                                                                           *
 *   Archipelago is distributed in the hope that it will be useful,          *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
 *   GNU Lesser General Public License for more details.                     *
 *                                                                           *
 *   You should have received a copy of the GNU Lesser General Public        *
 *   License along with Archipelago. If not, see                             *
 *   <http://www.gnu.org/licenses/>.                                         *
 *****************************************************************************/

/**
 * @file
 * @brief Object destructor function type.
 */

#pragma once
#ifndef _ARCHI_UTIL_DESTRUCTOR_TYP_H_
#define _ARCHI_UTIL_DESTRUCTOR_TYP_H_

/**
 * @brief Declare or define a memory mapping function.
 *
 * This macro expands to a function signature for a resource destructor:
 *
 * @param [in,out] data
 *   Pointer to destructor-specific data related to the destroyed resource.
 */
#define ARCHI_DESTRUCTOR_FUNC(func_name)    void func_name( \
        void *data)

/**
 * @brief Function pointer type for a resource destructor function.
 *
 * Points to a function with the signature generated by ARCHI_DESTRUCTOR_FUNC().
 *
 * @see ARCHI_DESTRUCTOR_FUNC
 */
typedef ARCHI_DESTRUCTOR_FUNC((*archi_destructor_func_t));

#endif // _ARCHI_UTIL_DESTRUCTOR_TYP_H_

