[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend= "setuptools.build_meta"

[project]
name="archi-builtin"
version="0.1.0"
description="Python bindings for the built-in modules of Archipelago"
dependencies=["archi-base"]
requires-python=">=3.13"

